name: Deploy
concurrency:
  group: deploy
  cancel-in-progress: true
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    env:
      STACK_NAME: walk-ups
      DOMAIN: aaronmamparo.com
      WEB_SUBDOMAIN: walk-ups
      API_SUBDOMAIN: walk-ups-api

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy AWS resources
        run: |
          cd .aws
          npm ci
          npm run deploy

      - name: Build & deploy web
        run: |
          cd web
          npm ci
          export MODE=production
          echo "VITE_API_BASE_URL=https://${API_SUBDOMAIN}.${DOMAIN}" >> .env.${MODE}
          npx vite build -m ${MODE}
          aws s3 sync --delete build "s3://${WEB_SUBDOMAIN}.${DOMAIN}"

      - name: Clear cloudfront cache
        run: |
          export DISTRIBUTION_ID=$(
            aws cloudformation describe-stacks \
              --stack-name ${STACK_NAME} \
              --query "Stacks[0].Outputs[?ExportName=='${STACK_NAME}-distribution-id'].OutputValue" \
              --output text
          )
          aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
